### ISSUE TITLE
SinOsc.ar

### ISSUE THREAD

**Issue by sonoro1234** [michaeldzjap/Phaser#1]
Hi Michael
I  think it is SinOsc.kr instead of SinOsc.ar for lfo (I get noise at the beggining if not doing that)

best
victor

**Comment by michaeldzjap** [comment]
Hey Victor,

I can't reproduce that. It sounds clean over here. I'm on OSX and using the latest SC build from source. Maybe that makes a difference somehow... Does this happen both for Phaser1 and Phaser2 for you?

The reason I used .ar is to experiment with audio rate lfo to see how that would sound, but for most uses a .kr version would suffice and be more efficient of course.

**Comment by sonoro1234** [comment]
Thats true, it only fails in Lua2SC. I must study this.

Thanks
